export const page = {
  link: "/faqs",
  title: "FAQs",
  description: "Frequently asked questions",
  thumbnail: "faqs-thumb.png",
  hero: {
    title: "FAQs",
    description: "Answers to common questions",
    descriptionCL: "mw-600",
    img: "question-marks.svg",
  },
  faq: [
    { id: "hows-perigon-different", question: "How’s Perigon different?", answer: "<p>The spirit of Perigon (and the reason we exist) is to help solve the problem of misinformation in the digital age. We believe that the modern social media news feed is fundamentally broken, and we want to be a part of the solution.</p><p>To that end, Perigon is different in the following key ways:</p><p><b>Ratings & reviews.</b> Perigon is the only mobile news app where you can react to media coverage based on the fairness, accuracy & quality of the story itself. Our system empowers you to rate journalists based on the truthfulness of their work, not on individual partisan leanings or how many eyeballs the story gets. Your participation helps to build a better media landscape for all.</p><p><b>Anti-echo chamber.</b> Unlike most major news feeds, the stories you read today won’t impact what you see tomorrow. We believe that existing, old-world algorithms foster confirmation bias, limit your view of the world, and give you only one side of the complex issues facing our world today.</p><p><b>Clearer, smarter labels.</b> We've put significant resources toward building intelligent labels that correctly tag opinion-based articles, non-news, celebrity gossip, and more. Articles in Perigon are clearly labeled to ensure that you know what came from where so you can effectively look for signs of biases and misinformation in the stories you read.</p>" },
    { id: "is-perigon-free", question: "Is Perigon free?", answer: "Yes, the Perigon news app is entirely free. Our first version is available for both Apple iOS and Android. The app is optimized for mobile and tablet devices. We also offer paid data and API <a href='/data-solutions/news-api'>solutions for businesses</a>." },
    { id: "is-there-political-bias", question: "Is there a political bias?", answer: "Perigon does not write or produce the news. Instead, we focus on building technology that makes it easier for you to stay informed without the concern of mystery algorithms under the hood. Many of our features are designed to provide 360° coverage across sources that have varying perspectives. We do not (and will never) hand-pick what you see or use technology that sorts and serves you content based on your likelihood to engage. The feeds on Perigon either sort by recency or - in the case of headlines - by the amount of recent coverage for a given story." },
    { id: "whats-the-business-model", question: "What’s the business model?", answer: "Perigon offers news and event data, along with API <a href='/data-solutions/news-api'>solutions for businesses</a>. These products offer a single access-point to the ~1,000,000 articles of news and content that our technology analyzes every day. Developers, analysts, and stakeholders can leverage our real-time feed of enriched, AI-powered news data to make more informed business decisions, uncover actionable insights, and enhance product strategies. We remain committed to building a new kind of tech company… one that doesn't make people the product. Perigon will never sell personal or sensitive data." },
    { id: "whys-it-called-perigon", question: "Why’s it called ‘Perigon’?", answer: "We’re building a new kind of tech company: one that’s hyper-focused on transparency, social impact & putting people first. We chose the name Perigon, a term meaning ‘an angle of 360 degrees,’ as a nod to our founding mission: to help people cut through the noise and capture a more complete, 360° view of what’s happening around the world. We exist to dismantle today’s media echo-chambers and create a space for people to be curious, decipher fact from fiction, compare news from all sides, and expand their perspective." },
    { id: "hows-perigon-funded", question: "How’s Perigon funded?", answer: "The company is founded and funded by Joshua Dziabiak, a serial entrepreneur and investor from Austin, TX." },
    { id: "which-media-sources-are-supported", question: "Which media sources are supported?", answer: "Perigon supports over 850 local, national & world media sources. These include major organizations like CNN, Fox News, ABC News, New York Post, NBC News, CBS News, Newsweek, and The New York Times. There are also dozens of specialized media sources available, like TechCrunch, ESPN, Snopes, Politico, Gadget, Refinery29, NPR, and others. To avoid overwhelming you with content, we do not automatically activate every source when you first register. You can enable, disable, or simply view the full list of available sources inside the 'Media' section under your account. If you'd like to request a new source to be added, please email <a href='mailto:support@perigon.com'>support@perigon.com</a>." },
    { id: "what-about-local-news", question: "What about local news?", answer: "Perigon's news app supports over 850 local, national & world media sources with an additional 40,000 sources supported by our <a href='/data-solutions/news-api'>business solutions</a> offering." },
    { id: "how-do-i-claim-journalist-profile", question: "How do I claim a journalist profile?", answer: "If you’re a journalist and looking to link your Perigon account to the journalist profile within the app, please email <a href='mailto:support@goperigon.com'>support@goperigon.com</a>. We’re building more interactive tools for journalists, so we look forward to connecting and building a relationship with you!" },
    { question: "More about Perigon", link: "/about/overview" },
    { question: "Contact us", link: "/about/contact" },
  ]
}
