const languages = {
  eng: {
    Home: "Home",
    Submit: "Submit",
    Name: "Name",
    yourEmail: "your@email.com",
    SelectOne: "Type of Inquiry",
    Typeyourmessagehere: "Type your message here",
    successMessage: "Thank you! We’ve received your message and will respond soon.",
    USD: "USD",
    month: "month",
    Startnow: "Start now",
    Monthly: "Monthly",
    Yearly: "Yearly",
    discount10: "10% discount",
    SignIn: "Sign In",
    APIplan: "API plan",
    Viewpricingplans: "View pricing plans",
    Firstname: "First name",
    Lastname: "Last name",
    Email: "Email",
    VerifiedEmail: "Email (verified)",
    NotVerifiedEmail: "Email (not verified)",
    Password: "Password",
    Passwordmustbe: "Password must be at least 6 characters, contain one special character and number",
    Ihaveread: "I have read & agree to the",
    Signup: "Sign up",
    EndUserAgreement: "End User License Agreement",
    BusinessName: "Business Name",
    ProjectName: "Project Name",
    HomeCountry: "Home Country",
    Complete: "Complete",
    SelectOne: "Type of Inquiry",
    Howdidyouhearaboutus: "How did you hear about us?",
    UseofAPI: "Use of API",
    SignOut: "Sign Out",
    Startplan: "Start plan",
    UpdatePlan: "Update plan",
    plan: "plan",
    APIplan: "API plan",
    BillingUSD: "Billing (USD)",
    Monthly: "Monthly",
    Yearly: "Yearly",
    mo: "mo",
    yr: "yr",
    Save10: "Save 10%",
    Billingdetails: "Billing details",
    CardNumber: "Card Number",
    CardholderName: "Cardholder Name",
    CVC: "CVC",
    Expiration: "Expiration",
    digitcode: "3 or 4-digit code",
    Update: "Update",
    Changepassword: "Change password",
    Status: "Status",
    Plan: "Plan",
    Billing: "Billing",
    Nextpayment: "Next Payment",
    Changeplan: "Change plan",
    Apiaccess: "Api access",
    OfRequests: "# OF REQUESTS",
    ViewKeys: "View Keys",
    APIDocs: "API Docs",
    APIUsage: "API Usage",
    Gettingstarted: "Getting started",
    Searchapi: "Search api",
    JournalistApi: "Journalist api",
    Postsnotfound: "Posts not found",
    Postnotfound: "The Post not found",
    m: "m",
    read: "read",
    Filedunder: "Filed under",
    Sharethis: "Share this",
    NotFound: "404 page not found",
    GetTheApp: "Get The App",
    ForEveryone: "For Everyone",
    ForBusiness: "For Business",
    Perigon: "Perigon",
    Notregisteredyet: "Not registered yet?",
    Signup: "Sign up",
    currentPassword: "Current Password",
    newPassword: "New Password",
    UpdatePassword: "Update Password",
    Passwordmustbe6: "Password must be at least 6 characters",
    Paymentsettings: "Payment settings",
    Pasttransactions: "Past transactions",
    NextPayment: "Next Payment",
    Billingisbeingmade: "Billing is being made to your credit card ending in",
    Nocardprovided: "No card information is provided",
    Transactiondate: "Transaction date",
    TransactionID: "Transaction ID",
    Description: "Description",
    Amount: "Amount",
    ResetPassword: "Reset Password",
    Unsubscribe: "Unsubscribe",
    Changepaymentmethod: "Change payment method",
    EmailVerificationWarningMessage: "Your email needs to be verified before your API key will work. Check your email (including spam) to verify.",
    TrialExpirationWarningMessage: "Your free trial expires on",
    Moreusecases: "More use cases",
    Readmore: "Read more",
    Followus: "Follow us",
    results: "results",
    Livedemo: "Live demo",
    Tophit: "Top hit",
    characters: "characters",
    MostlyPositive: "Mostly Positive",
    sentimentT: "sentiment",
    Relatedto: "Related to",
    otherarticles: "other articles",
    chars: "chars",
    Mostly: "Mostly",
    trialIncluded: "No credit card required, 15 days of free trial",
    Documentation: "Documentation",
    GetAPIKey: "Get API Key",
    AllContent: "All Content",
    HeadlineorArticle: "Headline or Article",
    wherethe: "where the",
    Contains: "Contains",
    Search: "Search",
    Enterquery: "Enter query",
    AddAnotherRule: "Add Another Rule",
    Filter: "Filter",
    Timeframe: "Timeframe",
    Location: "Location",
    Language: "Language",
    SourceMedia: "Source / Media",
    Category: "Category",
    Topic: "Topic",
    GET: "GET",
    Copy: "Copy",
    APIResponse: "API Response",
    Preview: "Preview",
    Top10results: "Top 10 results",
    APIMenu: "API Menu",
    Cancel: "Cancel",
    UsingAdvancedSearch: "Using Advanced Search",
    forT: "for",
    ft1: "Use 'All Content' for individual results, or search 'Headline Clusters' to find related stories/events grouped together",
    HeadlineClusters: "Headline Clusters",
    Save: "Save",
    Headline: "Headline",
    ft2: "Search the headline & article body for your query, or just the headline text",
    Advancedsearchtips: "Advanced search tips",
    where: "where",
    EditFilters: "Edit Filters",
    Startingon: "Starting on",
    Endingon: "Ending on",
    Cityname: "City name",
    letterstateprovince: "2-letter state/province",
    Allcountries: "All countries",
    Alllanguages: "All languages",
    Sourcegroups: "Source groups",
    Allcategories: "All categories",
    Alltopics: "All topics",
    d1: "Or define specific sources:",
    Include: "Include",
    Exclude: "Exclude",
    Addanother: "Add another",
    Sortby: "Sort by",
    Time: "Time",
    Relevance: "Relevance",
    Show: "Show",
    ofResults: "# of Results",
    FilterReprints: "Filter Reprints",
    Filters: "Filters",
    Myaccount: "My account",
    Copied: "Copied",
    NotFound: "Not Found",
    TheWire: "The Wire",
    Browsebytopic: "Browse by topic",
    by: "by",
    Findmoreabout: "Find more about",
    Export: "Export",
    ft3: "Download a sample of your results",
    Noresultsfound: "No results found",
    Tryadjusting: "Try adjusting your search criteria",
    Demounavailable: "Demo currently unavailable",
    Contactus: "Contact us",
    APIrequestsareprocessed: "API requests are processed using your account's API key",
    Share: "Share",
    ft4: "Share a direct link",
    CopyURL: "Copy URL",
    Articles: "Articles",
    Videos: "Videos",
    Refineresults: "Refine results",
    NoReprints: "No Reprints",
    NoPaywalledSources: "No Paywalled Sources",
    NoNonnews: "No Non-news",
    NoOpinions: "No Opinions",
    NoPaidNews: "No Paid News",
    label: "label",
    Excludefromresults: "Exclude from results",
    Video: "Video",
    Medium: "Medium",
    Showonlyvideos: "Show only videos",
    Excludevideos: "Exclude videos",
    Topic: "Topic",
    Removefromquery: "Remove from query",
    Addtoquery: "Add to query",
  }
}

export default languages;

