const languages = {
  eng: {
    Home: "Home",
    Submit: "Submit",
    Name: "Name",
    yourEmail: "your@email.com",
    SelectOne: "Select One",
    Typeyourmessagehere: "Type your message here",
    successMessage: "Thank you for contacting us, we will reach back to you in a short time.",
    USD: "USD",
    month: "month",
    Startnow: "Start now",
    Monthly: "Monthly",
    Yearly: "Yearly",
    discount10: "10% discount",
    SignIn: "Sign In",
    APIplan: "API plan",
    Viewpricingplans: "View pricing plans",
    Firstname: "First name",
    Lastname: "Last name",
    Email: "Email",
    Password: "Password",
    Passwordmustbe: "Password must be at least 6 characters, contain one special character and number",
    Ihaveread: "I have read & agree to the",
    Signup: "Sign up",
    EndUserAgreement : "End User License Agreement",
    BusinessName: "Business Name",
    HomeCountry: "Home Country",
    Complete: "Complete",
    SelectOne: "Select One",
    Howdidyouhearaboutus: "How did you hear about us?",
    UseofAPI: "Use of API",
    SignOut: "Sign Out",
    Startplan: "Start plan",
    plan: "plan",
    APIplan: "API plan",
    BillingUSD: "Billing (USD)",
    Monthly: "Monthly",
    Yearly: "Yearly",
    mo: "mo",
    yr: "yr",
    Save10: "Save 10%",
    Billingdetails: "Billing details",
    CardNumber: "Card Number",
    CardholderName: "Cardholder Name",
    CVC: "CVC",
    Expiration: "Expiration",
    digitcode: "3 or 4-digit code",
    Update: "Update",
    Changepassword: "Change password",
    Status: "Status",
    Plan: "Plan",
    Billing: "Billing",
    Nextpayment: "Next Payment",
    Changeplan: "Change plan",
    Apiaccess: "Api access",
    OfRequests: "# OF REQUESTS",
    ViewKeys :"View Keys",
    APIDocs: "API Docs",
    APIUsage: "API Usage"
  }
}

export default languages;

